
/* PARTICLES */
const cv=document.getElementById('bg'),cx=cv.getContext('2d');let W,H,pts=[];
function resize(){W=cv.width=innerWidth;H=cv.height=innerHeight}
function mkPts(){pts=[];const n=Math.floor(W*H/22000);for(let i=0;i<n;i++)pts.push({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,r:Math.random()*1.3+.4})}
function draw(){cx.clearRect(0,0,W,H);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=W;if(p.x>W)p.x=0;if(p.y<0)p.y=H;if(p.y>H)p.y=0;cx.beginPath();cx.arc(p.x,p.y,p.r,0,Math.PI*2);cx.fillStyle='rgba(0,180,255,.5)';cx.fill()});for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const dx=pts[i].x-pts[j].x,dy=pts[i].y-pts[j].y,d=Math.sqrt(dx*dx+dy*dy);if(d<90){cx.beginPath();cx.moveTo(pts[i].x,pts[i].y);cx.lineTo(pts[j].x,pts[j].y);cx.strokeStyle=`rgba(0,180,255,${.1*(1-d/90)})`;cx.lineWidth=.5;cx.stroke()}}requestAnimationFrame(draw)}
resize();mkPts();draw();addEventListener('resize',()=>{resize();mkPts()});

/* TICKER */
const tickData=[{s:'BTC',p:'$96,420',c:'+2.4%',up:1},{s:'ETH',p:'$3,847',c:'+1.8%',up:1},{s:'SOL',p:'$182',c:'+4.2%',up:1},{s:'EUR/USD',p:'1.0847',c:'-0.12%',up:0},{s:'S&P500',p:'6,852',c:'+0.3%',up:1},{s:'GOLD',p:'$3,120',c:'+0.8%',up:1},{s:'DAX',p:'22,847',c:'+0.6%',up:1},{s:'BNB',p:'$598',c:'-0.9%',up:0},{s:'XRP',p:'$2.34',c:'+3.1%',up:1},{s:'NASDAQ',p:'21,340',c:'+0.4%',up:1}];
const tr=document.getElementById('tickTr');[...tickData,...tickData].forEach(t=>{const d=document.createElement('div');d.className='t-item';d.innerHTML=`<span class="t-sym">${t.s}</span><span>${t.p}</span><span class="${t.up?'up':'dn'}">${t.c}</span>`;tr.appendChild(d)});

/* COUNTERS */
function cnt(el,val,sfx=''){let v=0,step=Math.ceil(val/55);const t=setInterval(()=>{v+=step;if(v>=val){v=val;clearInterval(t)}el.textContent=v.toLocaleString()+sfx},22)}
let cntDone=false;
new IntersectionObserver(e=>{if(e[0].isIntersecting&&!cntDone){cntDone=true;cnt(document.getElementById('k1'),247);cnt(document.getElementById('k2'),42);cnt(document.getElementById('k3'),18400,'+')}}).observe(document.getElementById('k1'));

/* AREA CHART */
function drawArea(svgId,data,colors){const svg=document.getElementById(svgId);if(!svg)return;const W=300,H=70,p=5,max=Math.max(...data),min=Math.min(...data),pts=data.map((v,i)=>{const x=p+i*(W-2*p)/(data.length-1),y=H-p-(v-min)/(max-min||1)*(H-2*p);return`${x},${y}`});const area=`M ${pts[0]} L ${pts.join(' L ')} L ${W-p},${H} L ${p},${H} Z`;svg.innerHTML=`<defs><linearGradient id="g${svgId}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${colors[1]}" stop-opacity="1"/><stop offset="100%" stop-color="transparent" stop-opacity="0"/></linearGradient></defs><path d="${area}" fill="url(#g${svgId})"/><polyline points="${pts.join(' ')}" fill="none" stroke="${colors[0]}" stroke-width="1.5"/>`}
drawArea('svgOv',[30,42,38,55,48,62,58,72,68,82,76,88],['var(--blue)','rgba(0,180,255,.15)']);

/* DONUT */
function drawDonut(svgId,segs){const svg=document.getElementById(svgId);if(!svg)return;const r=15.9,circ=2*Math.PI*r;let off=0;svg.innerHTML='<circle cx="18" cy="18" r="15.9" fill="none" stroke="rgba(255,255,255,.05)" stroke-width="3.8"/>';segs.forEach(s=>{const dash=s.p/100*circ,gap=circ-dash;svg.innerHTML+=`<circle cx="18" cy="18" r="${r}" fill="none" stroke="${s.c}" stroke-width="3.8" stroke-dasharray="${dash} ${gap}" stroke-dashoffset="${-off}" stroke-linecap="round"/>`;off+=dash})}
drawDonut('donutSvg',[{p:42,c:'var(--blue)'},{p:28,c:'var(--green)'},{p:18,c:'var(--gold)'},{p:12,c:'var(--purple)'}]);

/* HERO DASH TABS */
function switchDash(btn,id){document.querySelectorAll('.dash-tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.dash-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById('dp-'+id).classList.add('active');if(id==='ov')drawArea('svgOv',[30,42,38,55,48,62,58,72,68,82,76,88],['var(--blue)','rgba(0,180,255,.15)']);if(id==='perf')drawArea('svgPerf',[20,35,30,50,45,60,55,70,65,85,80,94],['var(--green)','rgba(0,229,160,.12)'])}

/* PROGRAMS */
const progs=[
  {id:1,flag:'🇱🇻',cat:'grant',badge:'Open',bc:'b-open',org:'LIAA · Latvia',name:'Innovation Voucher Aid Programme',desc:'Co-financing for SMEs to implement technology and digitalization. Covers consulting, prototyping, and market research.',max:'€25,000',dl:'30 Apr 2027',cof:'75%',tags:['SMEs','Tech','Digital','Latvian Co.'],stats:[{n:'Applications',v:'1,240'},{n:'Approved',v:'876'},{n:'Success Rate',v:'94%'}],bars:[{l:'Consulting',p:40,c:'bar-blue'},{l:'Prototyping',p:35,c:'bar-green'},{l:'Software',p:25,c:'bar-gold'}],donut:[{p:40,c:'var(--blue)'},{p:35,c:'var(--green)'},{p:25,c:'var(--gold)'}],suc:'94%',dates:'Opens: Ongoing · Closes: Apr 30, 2027'},
  {id:2,flag:'🇪🇺',cat:'grant',badge:'Open',bc:'b-open',org:'EIB · European Investment Bank',name:'Business Pre-Incubation Aid',desc:'Early-stage support for entrepreneurs validating ideas. Mentorship, workspace & seed funding for proof-of-concept projects.',max:'€10,000',dl:'Ongoing',cof:'100%',tags:['Startups','Early Stage','EU Citizens','Any Sector'],stats:[{n:'Slots Taken',v:'12/50'},{n:'Approved',v:'11'},{n:'Success Rate',v:'92%'}],bars:[{l:'Mentorship',p:50,c:'bar-green'},{l:'Workspace',p:30,c:'bar-blue'},{l:'Seed Capital',p:20,c:'bar-purple'}],donut:[{p:50,c:'var(--green)'},{p:30,c:'var(--blue)'},{p:20,c:'var(--purple)'}],suc:'92%',dates:'Opens: Now · Closes: Rolling basis'},
  {id:3,flag:'🌍',cat:'rnd',badge:'Coming Soon',bc:'b-soon',org:'Horizon Europe · R&D',name:'Deep Tech Innovation Grant Round 5',desc:'Funding for AI, biotech, cleantech, and advanced manufacturing. Supports both startups and established SMEs.',max:'€2.5M',dl:'Jun 2026',cof:'70%',tags:['AI / ML','BioTech','CleanTech','Advanced Mfg'],stats:[{n:'Total Budget',v:'€50M'},{n:'Expected Apps',v:'800'},{n:'Avg Grant',v:'€180K'}],bars:[{l:'AI & Digital',p:35,c:'bar-purple'},{l:'BioTech',p:30,c:'bar-green'},{l:'CleanTech',p:35,c:'bar-blue'}],donut:[{p:35,c:'var(--purple)'},{p:30,c:'var(--green)'},{p:35,c:'var(--blue)'}],suc:'N/A (opens Jun)',dates:'Opens: Jun 2026 · Deadline: Sep 2026'},
  {id:4,flag:'🇱🇻',cat:'export',badge:'Open',bc:'b-open',org:'LIAA · Export Division',name:'Export Support for Large Companies',desc:'International expansion: trade missions, market research co-financing for companies entering new foreign markets.',max:'€100,000',dl:'Ongoing',cof:'60%',tags:['Large Corps','Export','B2B','International'],stats:[{n:'Participants',v:'340'},{n:'Markets Entered',v:'48'},{n:'Success Rate',v:'88%'}],bars:[{l:'Market Research',p:30,c:'bar-blue'},{l:'Trade Missions',p:45,c:'bar-gold'},{l:'Marketing',p:25,c:'bar-green'}],donut:[{p:30,c:'var(--blue)'},{p:45,c:'var(--gold)'},{p:25,c:'var(--green)'}],suc:'88%',dates:'Opens: Ongoing · Closes: Jun 30, 2027'},
  {id:5,flag:'🌐',cat:'vc',badge:'Limited',bc:'b-ltd',org:'FUNDED.com · Angel Network',name:'Angel Investor Matching Programme',desc:'Curated matching with 1,200+ accredited angel investors. Structured pitch process with due diligence support.',max:'$500K',dl:'Rolling',cof:'N/A',tags:['Seed Stage','Series A','Tech','FinTech'],stats:[{n:'Investors',v:'1,200+'},{n:'Deals Closed',v:'347'},{n:'Avg Ticket',v:'$150K'}],bars:[{l:'Tech Startups',p:48,c:'bar-purple'},{l:'FinTech',p:28,c:'bar-blue'},{l:'Other',p:24,c:'bar-green'}],donut:[{p:48,c:'var(--purple)'},{p:28,c:'var(--blue)'},{p:24,c:'var(--green)'}],suc:'76%',dates:'Opens: Rolling · Min ARR: $50K'},
  {id:6,flag:'🏙️',cat:'loan',badge:'Open',bc:'b-open',org:'World Bank · SME Fund',name:'Municipal Entrepreneur Support',desc:'Support for businesses in municipalities and rural areas: subsidized loans, training, and infrastructure access.',max:'€50,000',dl:'Ongoing',cof:'N/A',tags:['Rural Areas','Municipalities','Any Sector','EU Wide'],stats:[{n:'Beneficiaries',v:'4,200'},{n:'Avg Loan',v:'€28K'},{n:'Repayment',v:'97%'}],bars:[{l:'Loans',p:55,c:'bar-blue'},{l:'Training',p:25,c:'bar-green'},{l:'Infrastructure',p:20,c:'bar-gold'}],donut:[{p:55,c:'var(--blue)'},{p:25,c:'var(--green)'},{p:20,c:'var(--gold)'}],suc:'97% repayment',dates:'Interest: 1.5% p.a. · Term: up to 5 years'},
];
let selProg=null;
function renderProgs(filter){const grid=document.getElementById('progGrid');grid.innerHTML='';(filter==='all'?progs:progs.filter(p=>p.cat===filter)).forEach(p=>{const c=document.createElement('div');c.className='prog-card'+(selProg===p.id?' selected':'');c.onclick=()=>openDetail(p,c);c.innerHTML=`<div class="prog-top"><span class="prog-flag">${p.flag}</span><span class="prog-badge ${p.bc}">${p.badge}</span></div><div class="prog-org">${p.org}</div><div class="prog-name">${p.name}</div><div class="prog-desc">${p.desc}</div><div class="prog-meta"><div class="pm"><div class="pm-lbl">Max Amount</div><div class="pm-val">${p.max}</div></div><div class="pm"><div class="pm-lbl">Deadline</div><div class="pm-val">${p.dl}</div></div><div class="pm"><div class="pm-lbl">Co-finance</div><div class="pm-val">${p.cof}</div></div></div><span class="prog-arrow">→ View Details</span>`;grid.appendChild(c)})}
function filterProgs(btn,cat){document.querySelectorAll('#programs .tab-btn').forEach(b=>b.classList.remove('on'));btn.classList.add('on');closeDetail();renderProgs(cat)}
function openDetail(p,card){document.querySelectorAll('.prog-card').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');selProg=p.id;const panel=document.getElementById('detailPanel');document.getElementById('det-title').textContent=p.name;document.getElementById('det-org').textContent=p.org+' · '+p.badge;document.getElementById('det-bars').innerHTML=p.bars.map(b=>`<div class="dp-bar-wrap"><div class="dp-bar-label"><span>${b.l}</span><span>${b.p}%</span></div><div class="dp-bar"><div class="dp-bar-fill ${b.c}" style="width:0" data-w="${b.p}%"></div></div></div>`).join('');document.getElementById('det-tags').innerHTML=p.tags.map(t=>`<span class="etag">${t}</span>`).join('');document.getElementById('det-dates').innerHTML=`<div class="dp-row"><span class="dp-name">Timeline</span><span class="dp-val" style="font-size:.82rem">${p.dates}</span></div>`;document.getElementById('det-stats').innerHTML=p.stats.map(s=>`<div class="dp-stat-item"><div class="dp-stat-num">${s.v}</div><div class="dp-stat-lbl">${s.n}</div></div>`).join('');drawDonut('detDonut',p.donut.map(d=>({p:d.p,c:d.c})));document.getElementById('detDonutLbl').textContent=p.max;const cols=['var(--blue)','var(--green)','var(--gold)','var(--purple)'];document.getElementById('detLegend').innerHTML=p.bars.map((b,i)=>`<div class="dl-row"><div class="dl-dot" style="background:${cols[i%4]}"></div><span class="dl-name">${b.l}</span><span class="dl-pct">${b.p}%</span></div>`).join('');document.getElementById('det-success').innerHTML=`<div class="dp-bar-wrap"><div class="dp-bar-label"><span>Success / Repayment Rate</span><span>${p.suc}</span></div><div class="dp-bar" style="height:10px"><div class="dp-bar-fill bar-green" style="width:0" data-w="${parseFloat(p.suc)||75}%"></div></div></div>`;panel.classList.add('open');panel.scrollIntoView({behavior:'smooth',block:'nearest'});setTimeout(()=>document.querySelectorAll('#detailPanel .dp-bar-fill').forEach(b=>{b.style.width=b.dataset.w||'0%'}),120)}
function closeDetail(){document.getElementById('detailPanel').classList.remove('open');selProg=null;document.querySelectorAll('.prog-card').forEach(c=>c.classList.remove('selected'))}
renderProgs('all');

/* MARKETS */
const mktData={
  crypto:[
    {name:'Bitcoin',sym:'BTC',icon:'₿',bg:'#f7931a',price:'$96,420',chg:'+2.41%',up:1,cap:'$1.9T',vol:'$42B',high:'$97,800',low:'$93,200',sparks:[2,4,3,5,4,6,7,8,7,9],chart:[50,60,45,70,55,80,65,90,75,95,80,100,85,95,90]},
    {name:'Ethereum',sym:'ETH',icon:'Ξ',bg:'#627eea',price:'$3,847',chg:'+1.83%',up:1,cap:'$462B',vol:'$18B',high:'$3,920',low:'$3,740',sparks:[5,4,6,5,7,6,8,7,8,9],chart:[40,55,45,65,55,75,60,80,70,85,75,90,80,88,85]},
    {name:'Solana',sym:'SOL',icon:'◎',bg:'#9945ff',price:'$182.40',chg:'+4.21%',up:1,cap:'$86B',vol:'$4.2B',high:'$188',low:'$172',sparks:[3,5,4,6,5,8,7,9,8,10],chart:[30,45,35,55,45,70,55,80,65,90,75,95,80,92,90]},
    {name:'BNB',sym:'BNB',icon:'B',bg:'#f3ba2f',price:'$598.20',chg:'-0.92%',up:0,cap:'$88B',vol:'$1.8B',high:'$612',low:'$590',sparks:[8,7,9,8,7,6,7,5,6,5],chart:[80,75,85,78,72,68,74,65,70,60,65,55,60,52,55]},
    {name:'XRP',sym:'XRP',icon:'✕',bg:'#00aae4',price:'$2.34',chg:'+3.10%',up:1,cap:'$135B',vol:'$6B',high:'$2.42',low:'$2.22',sparks:[4,5,4,6,5,7,6,8,7,9],chart:[35,45,40,55,48,62,55,70,62,78,68,82,72,88,84]},
    {name:'USDT',sym:'USDT',icon:'₮',bg:'#26a17b',price:'$1.000',chg:'+0.01%',up:1,cap:'$144B',vol:'$52B',high:'$1.001',low:'$0.999',sparks:[5,5,5,5,5,5,5,5,5,5],chart:[50,50,50,50,51,50,50,50,51,50,50,50,50,51,50]},
  ],
  stocks:[
    {name:'Apple Inc.',sym:'AAPL',icon:'🍎',bg:'#555',price:'$212.40',chg:'+0.84%',up:1,cap:'$3.2T',vol:'$62M',high:'$215',low:'$209',sparks:[5,6,5,7,6,8,7,8,8,9],chart:[60,65,62,70,66,74,70,78,74,82,78,84,80,86,84]},
    {name:'Microsoft',sym:'MSFT',icon:'⊞',bg:'#00a4ef',price:'$428.60',chg:'+1.12%',up:1,cap:'$3.1T',vol:'$24M',high:'$432',low:'$422',sparks:[4,5,5,6,6,7,7,8,8,9],chart:[55,60,58,65,62,70,66,74,70,78,75,80,78,84,82]},
    {name:'NVIDIA',sym:'NVDA',icon:'⬡',bg:'#76b900',price:'$880.20',chg:'+3.42%',up:1,cap:'$2.1T',vol:'$32M',high:'$895',low:'$842',sparks:[3,5,4,7,6,9,8,10,9,10],chart:[40,55,45,65,55,80,65,90,75,95,82,98,88,100,95]},
    {name:'Tesla',sym:'TSLA',icon:'⚡',bg:'#e31937',price:'$248.70',chg:'-1.84%',up:0,cap:'$792B',vol:'$82M',high:'$258',low:'$244',sparks:[8,7,6,8,7,6,5,6,5,4],chart:[80,72,78,68,75,65,72,60,68,55,62,50,58,48,52]},
    {name:'Alphabet',sym:'GOOGL',icon:'G',bg:'#4285f4',price:'$185.30',chg:'+0.62%',up:1,cap:'$2.3T',vol:'$18M',high:'$187',low:'$183',sparks:[5,6,5,6,6,7,6,7,7,8],chart:[55,58,56,62,60,65,62,68,65,70,68,72,70,74,72]},
  ],
  forex:[
    {name:'EUR / USD',sym:'EURUSD',icon:'€$',bg:'#003399',price:'1.0847',chg:'-0.12%',up:0,cap:'$1.8T/d',vol:'Major',high:'1.0892',low:'1.0821',sparks:[6,7,6,7,6,7,6,6,6,5],chart:[70,68,72,66,70,64,68,62,66,60,64,58,62,56,58]},
    {name:'GBP / USD',sym:'GBPUSD',icon:'£$',bg:'#012169',price:'1.2734',chg:'+0.08%',up:1,cap:'$1.2T/d',vol:'Major',high:'1.2760',low:'1.2698',sparks:[5,6,5,6,6,6,7,6,7,7],chart:[55,58,56,60,58,62,60,64,62,66,64,68,66,68,68]},
    {name:'USD / JPY',sym:'USDJPY',icon:'$¥',bg:'#bc002d',price:'152.84',chg:'+0.34%',up:1,cap:'$1.0T/d',vol:'Major',high:'153.40',low:'151.90',sparks:[4,5,5,6,5,7,6,7,7,8],chart:[45,50,48,55,52,60,56,64,60,68,64,70,66,72,70]},
    {name:'USD / CHF',sym:'USDCHF',icon:'$Fr',bg:'#d52b1e',price:'0.8924',chg:'-0.21%',up:0,cap:'$800B/d',vol:'Major',high:'0.8962',low:'0.8910',sparks:[7,6,7,6,6,5,6,5,5,4],chart:[68,65,70,62,66,58,64,54,60,50,56,48,52,46,50]},
  ],
  commodities:[
    {name:'Gold',sym:'XAU/USD',icon:'Au',bg:'#d4a017',price:'$3,120',chg:'+0.82%',up:1,cap:'Safe Haven',vol:'$220B',high:'$3,148',low:'$3,092',sparks:[4,5,5,6,6,7,7,8,8,9],chart:[55,60,58,65,62,70,66,74,70,78,75,80,78,84,82]},
    {name:'Silver',sym:'XAG/USD',icon:'Ag',bg:'#aaa',price:'$32.40',chg:'+1.24%',up:1,cap:'Industrial',vol:'$18B',high:'$33.10',low:'$31.80',sparks:[3,5,4,6,5,7,6,8,7,9],chart:[40,52,45,62,55,70,62,78,68,84,74,88,78,90,85]},
    {name:'Crude Oil WTI',sym:'WTI',icon:'🛢',bg:'#4a4a4a',price:'$78.40',chg:'-0.44%',up:0,cap:'Energy',vol:'$28B',high:'$80.10',low:'$77.80',sparks:[7,6,8,6,7,5,6,5,6,5],chart:[72,68,74,65,70,62,68,58,65,55,62,52,60,50,56]},
    {name:'Natural Gas',sym:'NATGAS',icon:'🔥',bg:'#ff6600',price:'$2.84',chg:'+2.10%',up:1,cap:'Energy',vol:'$12B',high:'$2.90',low:'$2.76',sparks:[3,4,4,5,5,7,6,8,7,9],chart:[35,42,38,50,44,60,52,72,62,82,70,88,76,90,84]},
  ]
};
let curCat='crypto',selRow=0;
function buildMktRows(cat){const rows=document.getElementById('mktRows');rows.innerHTML='';mktData[cat].forEach((m,i)=>{const div=document.createElement('div');div.className='mkt-row'+(i===selRow?' sel':'');div.onclick=()=>selectMkt(cat,i);const sp=m.sparks.map(h=>`<div class="sp" style="height:${h*2.3}px;background:${m.up?'var(--green)':'var(--red)'}"></div>`).join('');div.innerHTML=`<div class="coin"><div class="ci" style="background:${m.bg}22;color:${m.bg};border:1px solid ${m.bg}44;font-size:.75rem">${m.icon}</div><div><div class="cn">${m.name}</div><div class="cs">${m.sym}</div></div></div><div class="mkt-price">${m.price}</div><div class="mkt-chg ${m.up?'up':'dn'}">${m.up?'↑':'↓'} ${m.chg}</div><div class="spark-mini">${sp}</div>`;rows.appendChild(div)})}
function selectMkt(cat,idx){selRow=idx;buildMktRows(cat);const m=mktData[cat][idx];document.getElementById('md-name').textContent=m.name;const catLabel={crypto:'Cryptocurrency',stocks:'Stock',forex:'Forex Pair',commodities:'Commodity'};document.getElementById('md-sym').textContent=m.sym+' · '+catLabel[cat];document.getElementById('md-price').textContent=m.price;const chgEl=document.getElementById('md-chg');chgEl.className='md-chg-big '+(m.up?'up':'dn');chgEl.textContent=(m.up?'↑ ':'↓ ')+m.chg;document.getElementById('md-stats').innerHTML=`<div class="md-stat"><div class="md-stat-lbl">Market Cap</div><div class="md-stat-val">${m.cap}</div></div><div class="md-stat"><div class="md-stat-lbl">24h Volume</div><div class="md-stat-val">${m.vol}</div></div><div class="md-stat"><div class="md-stat-lbl">24h High</div><div class="md-stat-val" style="color:var(--green)">${m.high}</div></div><div class="md-stat"><div class="md-stat-lbl">24h Low</div><div class="md-stat-val" style="color:var(--red)">${m.low}</div></div>`;const svg=document.getElementById('mdChart');const d=m.chart,W=260,H=100,pad=8,max=Math.max(...d),min=Math.min(...d);const pts=d.map((v,i)=>{const x=pad+i*(W-2*pad)/(d.length-1),y=H-pad-(v-min)/(max-min||1)*(H-2*pad);return`${x},${y}`});const area=`M ${pts[0]} L ${pts.join(' L ')} L ${W-pad},${H} L ${pad},${H} Z`;const clr=m.up?'var(--green)':'var(--red)';svg.innerHTML=`<defs><linearGradient id="cg${idx}${cat}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${clr}" stop-opacity=".2"/><stop offset="100%" stop-color="${clr}" stop-opacity="0"/></linearGradient></defs><path d="${area}" fill="url(#cg${idx}${cat})"/><polyline points="${pts.join(' ')}" fill="none" stroke="${clr}" stroke-width="1.8"/>`}
function switchMkt(btn,cat){document.querySelectorAll('#markets .tab-btn').forEach(b=>b.classList.remove('on'));btn.classList.add('on');curCat=cat;selRow=0;buildMktRows(cat);selectMkt(cat,0)}
buildMktRows('crypto');selectMkt('crypto',0);
setInterval(()=>{document.querySelectorAll('.mkt-price').forEach(r=>{r.style.opacity='.4';setTimeout(()=>r.style.opacity='1',350)})},5000);

/* MONITOR */
const monData={
  gdp:{title:'GDP Growth by Region (%)',cols:['Region','Country','2024','2025 Est.','Trend'],rows:[['🌏 East Asia','China','5.2%','4.8%',85],['🌏 East Asia','India','7.8%','7.2%',90],['🌎 Americas','USA','2.5%','2.2%',65],['🌎 Americas','Brazil','2.1%','1.8%',55],['🇪🇺 Europe','Germany','0.4%','1.1%',42],['🇪🇺 Europe','Latvia','2.8%','3.2%',70],['🌍 Mid East','UAE','4.4%','5.0%',80],['🌏 SE Asia','Vietnam','5.8%','6.1%',88]]},
  inflation:{title:'Inflation Rate by Country (%)',cols:['Region','Country','Current Rate','Target','Risk'],rows:[['🇪🇺 EU','Germany','2.4%','2.0%',40],['🇪🇺 EU','France','2.2%','2.0%',38],['🌎 Americas','USA','3.4%','2.0%',55],['🌎 Americas','Argentina','72%','<10%',100],['🌍 Africa','Nigeria','31%','<9%',95],['🌏 Asia','Japan','2.8%','2.0%',48],['🌍 M. East','Turkey','42%','<10%',98],['🇪🇺 EU','Latvia','3.1%','2.0%',52]]},
  fdi:{title:'FDI Inflows by Destination ($B)',cols:['Region','Country','2024 Full Year','2025 Q1','Trend'],rows:[['🌏 East Asia','China','$163B','$44B',82],['🌎 Americas','USA','$311B','$80B',95],['🇪🇺 Europe','Germany','$68B','$18B',60],['🌏 SE Asia','Singapore','$92B','$24B',75],['🌍 M. East','UAE','$44B','$12B',70],['🌎 LatAm','Brazil','$62B','$14B',55],['🇪🇺 Baltic','Latvia','$2.8B','$0.7B',45],['🌍 Africa','Nigeria','$3.4B','$0.8B',38]]},
  trade:{title:'World Trade Volume Growth (%)',cols:['Category','Sector','2024','2025 Est.','Trend'],rows:[['📦 Goods','Electronics','+4.2%','+5.1%',82],['📦 Goods','Automotive','+1.8%','+2.4%',55],['💼 Services','Digital Svcs','+8.4%','+10.2%',95],['💼 Services','Finance','+5.2%','+6.0%',80],['🌿 Agri','Food & Bev','+2.4%','+2.8%',60],['⚡ Energy','LNG','+6.8%','+7.4%',88],['🔩 Raw Mat.','Rare Earths','+9.2%','+11.0%',98],['🚢 Logistics','Container Shipping','+3.4%','+4.1%',68]]},
};
function showMon(card,key){document.querySelectorAll('.mon-card').forEach(c=>c.classList.remove('active-mon'));card.classList.add('active-mon');const d=monData[key];document.getElementById('monTitle').innerHTML=`<span class="live-dot"></span>${d.title}`;document.getElementById('monTable').innerHTML=`<thead><tr>${d.cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${d.rows.map(r=>`<tr><td>${r[0]}</td><td><strong>${r[1]}</strong></td><td>${r[2]}</td><td style="color:var(--blue);font-weight:700">${r[3]}</td><td><div style="width:${r[4]*.55}px;height:6px;border-radius:3px;background:linear-gradient(90deg,var(--blue),var(--green));display:inline-block"></div></td></tr>`).join('')}</tbody>`}
showMon(document.querySelector('.mon-card'),'gdp');

/* EVENTS */
const evData=[
  {day:'14',mon:'May',cat:'forum',type:'Forum',title:'Latvia–Lithuania Business Forum 2026',loc:'📍 Vilnius, Lithuania'},
  {day:'21',mon:'May',cat:'trade',type:'Trade Mission',title:'EU–Asia Digital Trade Delegation',loc:'📍 Singapore'},
  {day:'06',mon:'Jun',cat:'summit',type:'Investment Summit',title:'Global Angel Investor Summit 2026',loc:'📍 Riga, Latvia'},
  {day:'18',mon:'Jun',cat:'trade',type:'Exhibition',title:'Baltic Tech & Innovation Expo',loc:'📍 Tallinn, Estonia'},
  {day:'02',mon:'Jul',cat:'summit',type:'Conference',title:'FinTech Europe 2026 — DeFi & Payments',loc:'📍 Amsterdam, Netherlands'},
  {day:'15',mon:'Jul',cat:'webinar',type:'Webinar',title:'EU Funding Navigator — Apply with Confidence',loc:'📍 Online'},
  {day:'28',mon:'Jul',cat:'forum',type:'Forum',title:'World Monitor Business Intelligence Summit',loc:'📍 Geneva, Switzerland'},
  {day:'05',mon:'Aug',cat:'webinar',type:'Workshop',title:'Angel Investment Masterclass for Founders',loc:'📍 Online'},
];
function renderEvs(filter){const g=document.getElementById('evGrid');g.innerHTML='';(filter==='all'?evData:evData.filter(e=>e.cat===filter)).forEach(e=>{const d=document.createElement('div');d.className='ev-card';d.innerHTML=`<div class="ev-date"><div class="ev-day">${e.day}</div><div class="ev-mon">${e.mon}</div></div><div><div class="ev-type">${e.type}</div><div class="ev-title">${e.title}</div><div class="ev-loc">${e.loc}</div></div>`;g.appendChild(d)})}
function filterEv(btn,cat){document.querySelectorAll('#events .tab-btn').forEach(b=>b.classList.remove('on'));btn.classList.add('on');renderEvs(cat)}
renderEvs('all');

/* REVEAL */
const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('vis')}),{threshold:.1});
document.querySelectorAll('.reveal').forEach(el=>ro.observe(el));

/* NAV */
function toggleMob(){document.getElementById('mob').classList.toggle('open')}
addEventListener('scroll',()=>{document.querySelector('nav').style.background=scrollY>50?'rgba(4,12,24,1)':'rgba(4,12,24,.9)'});
